var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/articles/2026-04-25/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0jn_7sl._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0-laso1.js")
R.c("server/chunks/ssr/app_articles_2026-04-25_page_tsx_0y65y8q._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0o63b-4._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0c7dpb-._.js")
R.c("server/chunks/ssr/_0fn9h_q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_articles_2026-04-25_page_actions_0l.4i4d.js")
R.m(65102)
module.exports=R.m(65102).exports
