var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/articles/2026-04-13/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__11a-vy3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0d2bd.7.js")
R.c("server/chunks/ssr/[root-of-the-server]__0o63b-4._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0c7dpb-._.js")
R.c("server/chunks/ssr/_0fn9h_q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_articles_2026-04-13_page_actions_0_park~.js")
R.m(32)
module.exports=R.m(32).exports
